import { expect, type APIRequestContext, type Page } from '@playwright/test';

import { PARTNER_BASE as BASE } from './partner-session.js';

/**
 * Finding a fixture listing without writing its reference into a spec.
 *
 * ## Why this exists
 *
 * References are generated by the database, so `db:testbed` produces different ones on every run.
 * A spec that hard-coded `PRO-003297` passed for exactly as long as nobody reseeded, and then
 * failed with a 404 that looked like a broken screen rather than a stale constant — which is what
 * happened the first time a fixture was added to the seed.
 *
 * Slugs, by contrast, are written in the seed and are stable. So specs name a SLUG and this
 * resolves it.
 *
 * Not a `*.spec.ts` file on purpose: Playwright collects those, and a spec importing another spec
 * is refused. `partner-session.ts` exists for the same reason.
 */

/** Enough of each fixture listing's Arabic name to tell it apart on the registry. */
const NAMES: Record<string, string> = {
  'qasr-al-sharq-malki': 'المالكي',
  'qasr-al-sharq-abu-rummaneh': 'أبو رمانة',
  'qasr-al-sharq-apartments': 'المخدومة',
  'qasr-al-sharq-lodge': 'قيد الإعداد',
  'qasr-al-sharq-rest-house': 'مرفوضة',
};

/**
 * The reference of the partner's listing with this slug.
 *
 * Published listings are readable through the public API, which is one request. A draft or
 * rejected one is not — correctly, it is not published — so those are found by walking the
 * partner's own registry and matching the name the seed gave them.
 */
export async function findReference(page: Page, slug: string): Promise<string> {
  const published = await publishedReference(page.request, slug);

  if (published) return published;

  await page.goto(`${BASE}/properties`);

  const hrefs = await page
    .locator('a[href*="/properties/PRO-"]')
    .evaluateAll((nodes) =>
      nodes.map((node) => (node as HTMLAnchorElement).getAttribute('href') ?? ''),
    );

  const references = [
    ...new Set(
      hrefs
        .map((href) => /\/properties\/(PRO-\d+)/.exec(href)?.[1])
        .filter((value): value is string => Boolean(value)),
    ),
  ];

  const name = NAMES[slug];

  for (const reference of references) {
    await page.goto(`${BASE}/properties/${reference}/edit`);

    const heading = await page.locator('h2').first().textContent();

    if (name && heading?.includes(name)) return reference;
  }

  /*
    Fails loudly rather than returning the first reference it saw. A helper that quietly returned
    the wrong listing would make the assertions that follow describe something nobody asked about,
    and the failure would be reported against them instead of against this.
  */
  expect(references, `no fixture listing matched the slug ${slug}`).toHaveLength(0);

  return '';
}

/**
 * The reference of a PUBLISHED listing, from the public endpoint — or null if it is not published.
 *
 * Split out so a spec with no page can ask: `beforeAll` has a `request` fixture and no browser, and
 * several specs only ever need a published listing. `findReference` above falls back to walking the
 * partner's registry, which a draft needs and a request cannot do.
 *
 * ## Why no spec may write a reference down
 *
 * `db:testbed` deletes its fixture listings and creates them again, and `properties.reference` is
 * generated on insert — so every reset renumbers them. On 2026-09-06 a reseed turned `PRO-598653`
 * into `PRO-601709`, and five specs that had one written down began opening «هذه الصفحة غير موجودة»
 * against a console that was working perfectly. A slug is derived from the name and written
 * verbatim, so the slug is the identity a spec should hold.
 */
export async function publishedReference(
  request: APIRequestContext,
  slug: string,
): Promise<string | null> {
  const response = await request.get(
    `http://localhost:4000/api/v1/properties/${encodeURIComponent(slug)}`,
  );

  if (!response.ok()) return null;

  const { reference } = (await response.json()) as { reference?: string };

  return typeof reference === 'string' && reference.length > 0 ? reference : null;
}

/** The same, but refusing to continue when it is missing — for a spec that cannot go on without it. */
export async function requirePublishedReference(
  request: APIRequestContext,
  slug: string,
): Promise<string> {
  const reference = await publishedReference(request, slug);

  if (!reference) throw new Error(`No published property for slug "${slug}".`);

  return reference;
}

/**
 * A partner's §13.2 reference, found by their display name on the console registry.
 *
 * `partners.reference` is generated on insert and `db:testbed` recreates its fixture partners, so
 * every reset renumbers them exactly as it does properties — `PAR-433898` became `PAR-730422` on
 * 2026-09-06, and a spec holding the old one opened «هذه الصفحة غير موجودة» against a console that
 * was working. The display name is written verbatim by the seeder and survives.
 *
 * Needs a STAFF page: there is no public partner endpoint, and there should not be.
 */
export async function findPartnerReference(page: Page, name: string): Promise<string> {
  await page.goto(`http://localhost:3001/partners?q=${encodeURIComponent(name)}`, {
    waitUntil: 'domcontentloaded',
  });

  const href = await page
    .locator('a[href*="/partners/PAR-"]')
    .first()
    .getAttribute('href');

  const reference = /\/partners\/(PAR-\d+)/.exec(href ?? '')?.[1];

  if (!reference) throw new Error(`No partner on the registry named "${name}".`);

  return reference;
}
