import { expect, test, type Locator, type Page } from '@playwright/test';

import { partnerAr as t } from '../packages/i18n/src/partner.js';
import { findReference } from './partner-fixtures.js';
import { PARTNER_BASE, PARTNER_STATE } from './partner-session.js';

/**
 * معرض صور العقار — the upload pipeline, driven the way a partner drives it.
 *
 * ## Why this test exists
 *
 * Everything the image manager does was already covered by service tests, and none of that
 * coverage touched the part most likely to break. `PropertyImageService` is exercised with a
 * `Buffer` handed straight to it; the real path is a `<input type="file">` in a client component →
 * `FormData` → a Next route handler that rebuilds the multipart body → the API's
 * `FileInterceptor` → sharp. Four boundaries the service tests skip, each one able to fail while
 * every other test in the repository stays green.
 *
 * The specific failure that motivated it: a proxy route that forwards a parsed body instead of the
 * stream arrives at the API as a file-less request, and the API answers 400 «تعذّر رفع الصورة».
 * From the service's point of view nothing is wrong, because the service is never reached.
 *
 * ## Real bytes, not a stub
 *
 * `e2e/fixtures/*.jpg` are actual JPEGs generated by sharp, over the 400px floor the pipeline
 * enforces. A zero-byte file with an image name would prove the form posts and prove nothing about
 * decoding, resizing or the variant set — which is the expensive half.
 *
 * `too-small.jpg` is 120×120 and must be REFUSED. A pipeline that accepts anything is not
 * validating, and the only way to see the difference from outside is to hand it something invalid.
 *
 * ## Idempotent, because `pnpm e2e` does not re-seed
 *
 * The suite runs against a live testbed that is seeded separately, so a spec which assumed an
 * empty gallery would pass once and fail for ever after. This one normalises first and asserts
 * RELATIVE to what it finds. It cannot normalise to zero: a published listing refuses to archive
 * its last image — which is itself one of the things asserted below.
 */

test.use({ storageState: PARTNER_STATE });

/**
 * A listing owned by `partner1`, seeded with no images.
 *
 * Named by SLUG, resolved to a reference at run time. References are database-generated and change
 * on every reseed — a hard-coded one passed until the seed gained a fixture, then failed as a 404
 * that looked like a broken screen.
 *
 * Deliberately not the listing the other partner specs read: a spec that uploads into a listing
 * another spec counts rows on is a spec that fails for reasons in a different file.
 */
const SLUG = 'qasr-al-sharq-apartments';

/** Every card currently rendered. The manager draws one `<li>` per live image. */
function cards(page: Page): Locator {
  return page.locator('li').filter({ has: page.locator('img') });
}

/** The thumbnail sources on the page, which identify a card without depending on its position. */
async function sources(page: Page): Promise<string[]> {
  return cards(page)
    .locator('img')
    .evaluateAll((nodes) =>
      nodes.map((node) => (node as HTMLImageElement).getAttribute('src') ?? ''),
    );
}

/**
 * The manager's own error banner.
 *
 * Scoped to the `<p>` rather than `getByRole('alert')`: Next renders a permanently-present, empty
 * `<div role="alert">` route announcer, so the bare role matches two elements and every assertion
 * against it is a strict-mode violation rather than a result.
 */
function alertText(page: Page): Locator {
  return page.locator('p[role="alert"]');
}

/** The one card showing a given thumbnail. */
function cardFor(page: Page, src: string): Locator {
  return cards(page).filter({ has: page.locator(`img[src="${src}"]`) });
}

/** Uploads a fixture and returns the thumbnail source of the card that appeared. */
async function upload(page: Page, fixture: string): Promise<string> {
  const before = await sources(page);

  await page.locator('input[type="file"]').setInputFiles(`e2e/fixtures/${fixture}`);

  /* Processing is real work — decode, resize, re-encode, store — so this is not instant. */
  await expect(cards(page)).toHaveCount(before.length + 1, { timeout: 30_000 });

  const after = await sources(page);
  const added = after.filter((src) => !before.includes(src));

  expect(added).toHaveLength(1);

  return added[0] as string;
}

/**
 * Brings the gallery down to the fewest images it will hold.
 *
 * Runs before the assertions rather than after them: an "after" cleanup does not run when a test
 * fails, and the run after a failure would then start from a state no assertion described.
 */
async function normalise(page: Page): Promise<void> {
  /*
    Bounded rather than `while (true)`: if archiving ever stopped both removing a card AND raising
    an alert, an unbounded loop would hang the run until the whole suite timed out, which reads as
    infrastructure trouble rather than as the bug it is. MAX images is the most there can be.
  */
  for (let attempt = 0; attempt < 20; attempt += 1) {
    const before = await cards(page).count();

    if (before === 0) return;

    await cards(page).first().getByRole('button', { name: t.images.archive }).click();

    /* It either goes, or the listing refuses to give up its last image. */
    await expect
      .poll(
        async () =>
          (await cards(page).count()) < before || (await alertText(page).count()) > 0,
        { timeout: 15_000 },
      )
      .toBe(true);

    if ((await cards(page).count()) === before) return;
  }
}

test.describe('معرض صور العقار', () => {
  test.beforeEach(async ({ page }) => {
    /* Registered once for the whole test: accepting an already-handled dialog throws. */
    page.on('dialog', (dialog) => void dialog.accept());

    const reference = await findReference(page, SLUG);

    await page.goto(`${PARTNER_BASE}/properties/${reference}/images`);
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
    await normalise(page);
  });

  test('يرفع صورة حقيقية عبر النموذج ويعرضها', async ({ page }) => {
    const before = await cards(page).count();

    const src = await upload(page, 'room-one.jpg');

    /*
      The card is not enough on its own: the manager could render a card for a row the pipeline
      never stored. The thumbnail has to actually LOAD, which only happens if the variant was
      written to the media host and is publicly readable.
    */
    const image = cardFor(page, src).locator('img');

    await expect(image).toBeVisible();
    await expect
      .poll(async () => image.evaluate((node) => (node as HTMLImageElement).naturalWidth))
      .toBeGreaterThan(0);

    await expect(cards(page)).toHaveCount(before + 1);

    /* And it survives a reload — i.e. it was stored, not just added to React state. */
    await page.reload();
    await expect(cardFor(page, src)).toHaveCount(1);
  });

  test('يرفض صورة أصغر من الحد الأدنى ويشرح السبب', async ({ page }) => {
    const before = await cards(page).count();

    await page.locator('input[type="file"]').setInputFiles('e2e/fixtures/too-small.jpg');

    await expect(alertText(page)).toBeVisible({ timeout: 30_000 });

    /* Refused means refused: no half-written row, no card. */
    await expect(cards(page)).toHaveCount(before);

    await page.reload();
    await expect(cards(page)).toHaveCount(before);
  });

  test('يحفظ وصف الصورة بالعربية والإنجليزية والألمانية', async ({ page }) => {
    const src = await upload(page, 'room-one.jpg');
    const card = cardFor(page, src);

    const arabic = 'غرفة نوم مطلة على الحديقة';
    const english = 'Bedroom overlooking the garden';
    const german = 'Schlafzimmer mit Gartenblick';

    await card.getByLabel(t.images.altAr).fill(arabic);
    await card.getByLabel(t.images.altEn).fill(english);
    await card.getByLabel(t.images.altDe).fill(german);
    await card.getByRole('button', { name: t.images.altSave }).click();

    await expect(card.getByRole('button', { name: t.images.altSaved })).toBeVisible();

    /*
      All THREE, after a reload. The bug this replaces was a form that edited three fields and sent
      one — which looks identical on screen until somebody reads the listing in German.
    */
    await page.reload();

    const reloaded = cardFor(page, src);

    await expect(reloaded.getByLabel(t.images.altAr)).toHaveValue(arabic);
    await expect(reloaded.getByLabel(t.images.altEn)).toHaveValue(english);
    await expect(reloaded.getByLabel(t.images.altDe)).toHaveValue(german);

    /* The Arabic one is what the manager's own thumbnail announces to a screen reader. */
    await expect(reloaded.locator('img')).toHaveAttribute('alt', arabic);
  });

  test('يعيد الترتيب ويثبت بعد التحديث', async ({ page }) => {
    const first = await upload(page, 'room-one.jpg');
    const second = await upload(page, 'room-two.jpg');

    /* Positions of the two we uploaded, ignoring whatever the listing already held. */
    const order = async () => {
      const all = await sources(page);

      return { first: all.indexOf(first), second: all.indexOf(second) };
    };

    const start = await order();

    expect(start.first).toBeLessThan(start.second);

    await cardFor(page, first).getByRole('button', { name: t.images.moveDown }).click();

    await expect
      .poll(async () => {
        const now = await order();

        return now.first > now.second;
      })
      .toBe(true);

    /* Stored, not just reordered in the browser. */
    await page.reload();

    const after = await order();

    expect(after.first).toBeGreaterThan(after.second);
  });

  test('يغيّر صورة الغلاف بالزر لا بالترتيب', async ({ page }) => {
    const first = await upload(page, 'room-one.jpg');
    const second = await upload(page, 'room-two.jpg');

    /*
      `exact` matters: the badge reads «صورة الغلاف» and the button reads «اجعلها صورة الغلاف»,
      so a substring match finds the control on every card that is NOT the cover.
    */
    const badge = (src: string) =>
      cardFor(page, src).getByText(t.images.cover, { exact: true });

    await cardFor(page, second).getByRole('button', { name: t.images.makeCover }).click();

    await expect(badge(second)).toBeVisible();

    /* Exactly one cover on the page — the partial unique index says so, and so should the UI. */
    await expect(page.getByText(t.images.cover, { exact: true })).toHaveCount(1);
    await expect(badge(first)).toHaveCount(0);

    await page.reload();
    await expect(badge(second)).toBeVisible();

    /*
      Reordering must NOT move the cover. The two are separate columns and the screen now says so;
      this is the assertion that keeps the sentence and the behaviour together.

      «تقديم» rather than «تأخير»: uploads append, so `second` is last and its move-down control is
      correctly disabled. Clicking a disabled button asserts nothing and times out.
    */
    await cardFor(page, second).getByRole('button', { name: t.images.moveUp }).click();
    await page.reload();
    await expect(badge(second)).toBeVisible();
  });

  test('يؤرشف صورة ويرفض أرشفة الأخيرة لعقار منشور', async ({ page }) => {
    const first = await upload(page, 'room-one.jpg');

    await upload(page, 'room-two.jpg');

    const total = await cards(page).count();

    await cardFor(page, first).getByRole('button', { name: t.images.archive }).click();

    await expect(cards(page)).toHaveCount(total - 1);
    await expect(cardFor(page, first)).toHaveCount(0);

    /* A soft delete, so it stays gone across a reload rather than reappearing from the server. */
    await page.reload();
    await expect(cardFor(page, first)).toHaveCount(0);

    /* Down to one, where a published listing stops. */
    while ((await cards(page).count()) > 1) {
      const before = await cards(page).count();

      await cards(page).first().getByRole('button', { name: t.images.archive }).click();
      await expect(cards(page)).toHaveCount(before - 1);
    }

    await cards(page).first().getByRole('button', { name: t.images.archive }).click();

    await expect(alertText(page)).toContainText(t.images.lastImage);
    await expect(cards(page)).toHaveCount(1);
  });

  test('يرفع عدة صور دفعة واحدة ويحافظ على الترتيب', async ({ page }) => {
    const before = await cards(page).count();

    /*
      Two files in ONE selection. The manager sends them sequentially, which is what keeps the two
      invariants true — the first image becomes the cover, and each new one goes after the last.
      Uploaded in parallel they race, and the resulting order is whatever the event loop decided.
    */
    await page
      .locator('input[type="file"]')
      .setInputFiles(['e2e/fixtures/room-one.jpg', 'e2e/fixtures/room-two.jpg']);

    await expect(cards(page)).toHaveCount(before + 2, { timeout: 60_000 });

    /* Both survive a reload, so both were stored rather than one being dropped silently. */
    await page.reload();
    await expect(cards(page)).toHaveCount(before + 2);

    /* Still exactly one cover — a batch must not create a second. */
    await expect(page.getByText(t.images.cover, { exact: true })).toHaveCount(1);
  });

  test('يقبل ما يتسع ويقول كم رُفع عندما تتجاوز الدفعة الحد', async ({ page }) => {
    /*
      The refusal has to be legible. A batch that silently drops the overflow leaves the partner
      believing photographs are there that are not, and the count under the button is the only
      place they would ever find out.
    */
    const files = Array.from({ length: 3 }, () => 'e2e/fixtures/room-one.jpg');

    await page.locator('input[type="file"]').setInputFiles(files);

    await expect(cards(page)).not.toHaveCount(0, { timeout: 60_000 });

    const shown = await cards(page).count();

    await page.reload();

    /* What the screen said and what was stored are the same number. */
    await expect(cards(page)).toHaveCount(shown);
  });
});
