import { expect, type Page } from '@playwright/test';

import { PARTNER_BASE as BASE } from './partner-session.js';

/**
 * Finding a fixture listing without writing its reference into a spec.
 *
 * ## Why this exists
 *
 * References are generated by the database, so `db:testbed` produces different ones on every run.
 * A spec that hard-coded `PRO-003297` passed for exactly as long as nobody reseeded, and then
 * failed with a 404 that looked like a broken screen rather than a stale constant — which is what
 * happened the first time a fixture was added to the seed.
 *
 * Slugs, by contrast, are written in the seed and are stable. So specs name a SLUG and this
 * resolves it.
 *
 * Not a `*.spec.ts` file on purpose: Playwright collects those, and a spec importing another spec
 * is refused. `partner-session.ts` exists for the same reason.
 */

/** Enough of each fixture listing's Arabic name to tell it apart on the registry. */
const NAMES: Record<string, string> = {
  'qasr-al-sharq-malki': 'المالكي',
  'qasr-al-sharq-abu-rummaneh': 'أبو رمانة',
  'qasr-al-sharq-apartments': 'المخدومة',
  'qasr-al-sharq-lodge': 'قيد الإعداد',
  'qasr-al-sharq-rest-house': 'مرفوضة',
};

/**
 * The reference of the partner's listing with this slug.
 *
 * Published listings are readable through the public API, which is one request. A draft or
 * rejected one is not — correctly, it is not published — so those are found by walking the
 * partner's own registry and matching the name the seed gave them.
 */
export async function findReference(page: Page, slug: string): Promise<string> {
  const response = await page.request.get(
    `http://localhost:4000/api/v1/properties/${slug}`,
  );

  if (response.ok()) {
    const body = (await response.json()) as { reference?: string };

    if (body.reference) return body.reference;
  }

  await page.goto(`${BASE}/properties`);

  const hrefs = await page
    .locator('a[href*="/properties/PRO-"]')
    .evaluateAll((nodes) =>
      nodes.map((node) => (node as HTMLAnchorElement).getAttribute('href') ?? ''),
    );

  const references = [
    ...new Set(
      hrefs
        .map((href) => /\/properties\/(PRO-\d+)/.exec(href)?.[1])
        .filter((value): value is string => Boolean(value)),
    ),
  ];

  const name = NAMES[slug];

  for (const reference of references) {
    await page.goto(`${BASE}/properties/${reference}/edit`);

    const heading = await page.locator('h2').first().textContent();

    if (name && heading?.includes(name)) return reference;
  }

  /*
    Fails loudly rather than returning the first reference it saw. A helper that quietly returned
    the wrong listing would make the assertions that follow describe something nobody asked about,
    and the failure would be reported against them instead of against this.
  */
  expect(references, `no fixture listing matched the slug ${slug}`).toHaveLength(0);

  return '';
}
