/**
 * Every SAFRA logo file the apps serve, from the one source of record (Bashar, 2026-10-07).
 *
 *   pnpm --filter @safra/ui build && node scripts/generate-brand.mjs
 *
 * `packages/ui/brand/` holds his logo as his designer delivered it (`svg/`, `png/`, README). The
 * logo on screen is `SafraLockup` in `@safra/ui`; this script puts the rest where it is needed and
 * commits the result, so no build step and no container needs an image library or React:
 *
 * - `apps/{web,admin,partner}/src/app/icon.svg` and `apple-icon.png`: Next's file-based icons, his
 *   favicon (the pin on a night tile, which reads on any tab colour) and his touch icon.
 * - `apps/api/src/brand/logo-markup.ts`: `SafraLockup` rendered to static markup for the voucher and
 *   the contract. Those are HTML printed by the API's own Chromium, so the PDF shows the exact
 *   lockup the site shows, as vectors, rather than a picture of it.
 */
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BRAND = join(ROOT, 'packages/ui/brand');

for (const app of ['web', 'admin', 'partner']) {
  copyFileSync(
    join(BRAND, 'svg/favicon.svg'),
    join(ROOT, `apps/${app}/src/app/icon.svg`),
  );
  copyFileSync(
    join(BRAND, 'png/apple-touch-icon-180.png'),
    join(ROOT, `apps/${app}/src/app/apple-icon.png`),
  );
}

/* React from the customer app, which has it; the UI package's build is what renders. */
const fromWeb = createRequire(join(ROOT, 'apps/web/package.json'));
const { createElement } = fromWeb('react');
const { renderToStaticMarkup } = fromWeb('react-dom/server');
const { SafraLockup } = await import(
  pathToFileURL(join(ROOT, 'packages/ui/dist/safra-lockup.js')).href
);

/* «SAFRA» is the brand's own spelling in every language: the documented wordmark exception. */
const markup = renderToStaticMarkup(
  createElement(SafraLockup, { latin: 'SAFRA', layout: 'stacked', print: true }),
);

mkdirSync(join(ROOT, 'apps/api/src/brand'), { recursive: true });
writeFileSync(
  join(ROOT, 'apps/api/src/brand/logo-markup.ts'),
  `/* Generated by scripts/generate-brand.mjs from SafraLockup (2026-10-07). Do not edit. */\n` +
    `export const SAFRA_LOCKUP_MARKUP =\n  ${JSON.stringify(markup)};\n`,
);

console.log('icons copied to 3 apps; lockup markup', markup.length, 'chars');
